open_graph:
  enable: true
  twitter_id: # for open_graph meta

## 侧边栏 ###

# Logo
logo:
  avatar: '[https://avatars.githubusercontent.com/u/89719720?v=4](https://github.com/shenpengfii/)'
  title: '[偷本非礼](/)'
  subtitle: '正是江南好风景 | 落花时节又逢君'

# 导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

### 评论区 ###

comments:
  service: giscus
  giscus:
    src: https://giscus.app/client.js
    data-repo: shenpengfii/shenpengfii.github.io
    data-category: Announcements
    data-category-id: DIC_kwDOMB04tc4ChCRi
    data-mapping: title
    data-strict: 1
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: light_protanopia
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

### 全局样式 ###

style:
  prefers_theme: light
  smooth_scroll: true
  font-size:
      root: 16px # 改这个会影响全局所有文字的字号
      body: 17px # 影响正文区域的字号，如果改成 px 则不受 root 影响
      code: 90% # 相较于其所在行的文本大小，建议用百分比
      codeblock: 13px
  font-family:
      logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
      body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
      code: '"Fira Code Light", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
      codeblock: '"Fira Code", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  border-radius:
    card-l: 20px # 侧边栏、文章横幅位置的圆角
    card: 12px # 文章内大部分卡片的圆角
    bar: 16px # 横条类元素的圆角
    image: 6px # 图片圆角
  color:
    # 动态颜色（会根据明暗主题重设明度值，只用关心色相和饱和度即可）
    background: 'hsl(0, 0%, 100%)' # 浅色背景颜色
    block: 'hsl(347, 61%, 93%)' # 块背景颜色
    code: 'hsl(14 100% 30%)' # 'hsl(14 100% 48%)' # 行内代码颜色
    text: 'hsl(0 0% 0%)' # 文本颜色
  leftbar:
    background-image: 'linear-gradient(45deg, pink, blue)'
  site:
    background-image: url('https://ooo.0x0.ooo/2024/08/18/Oty0Zs.jpg')
    blur-px: 0px
    blur-bg: var(--alpha50)

### 文章配置 ###

article:
  auto_cover: false
  share: [wechat, weibo, email, link]

### 插件 ###
tag_plugins:
  # image 标签
  image:
    fancybox: true