### 侧边栏 ###

# Logo
logo:
  avatar: '[https://avatars.githubusercontent.com/u/89719720?v=4](https://github.com/shenpengfii/)'
  title: '[小写的圆周率](/)'
  subtitle: '正是江南好风景 | 落花时节又逢君'

# 导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /

### 全局样式 ###

style:
  prefers_theme: light
  smooth_scroll: true
  font-size:
      root: 16px # 改这个会影响全局所有文字的字号
      body: 16px # 影响正文区域的字号，如果改成 px 则不受 root 影响
      code: 90% # 相较于其所在行的文本大小，建议用百分比
      codeblock: 13px
  font-family:
      logo: 'STZhongSong, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
      body: 'STZhongSong, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
      code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
      codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  border-radius:
    card-l: 20px # 侧边栏、文章横幅位置的圆角
    card: 12px # 文章内大部分卡片的圆角
    bar: 16px # 横条类元素的圆角
    image: 6px # 图片圆角
  color:
    # 动态颜色（会根据明暗主题重设明度值，只用关心色相和饱和度即可）
    background: 'hsl(191, 100%, 85%)' # 浅色背景颜色
    block: 'hsl(347, 61%, 93%)' # 块背景颜色
    code: 'hsl(14 100% 30%)' # 'hsl(14 100% 48%)' # 行内代码颜色
    text: 'hsl(0 0% 0%)' # 文本颜色
  leftbar:
    background-image: 'linear-gradient(45deg, pink, lightblue)'
  site:
    background-image: url('/asserts/background.jpg')
    blur-px: 0px
    blur-bg: var(--alpha50)