logo:
  avatar: '[https://avatars.githubusercontent.com/u/89719720?v=4](https://github.com/shenpengfii/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[小写的圆周率](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: '正是江南好风景 | 落花时节又逢君' # '文字1 | 文字2' (鼠标放上去会切换到文字2)

style:
  leftbar:
    background-image: url(https://bizhi1.com/wp-content/uploads/2024/03/bizhi1-03-anime-small.jpg)
    blur-px: 100px # 模糊半径
    blur-bg: var(--alpha60) # 模糊颜色
